{
  this("An exception occurred in a callback",cause);
}
